### ISSUE TITLE
Photometric Interpretation = Palette Color Scrubs the Look up Tables

### ISSUE THREAD

**Issue by cancan101** [chop-dbhi/dicom-anon#14]
Per https://www.dabsoft.ch/dicom/3/C.7.6.3.1.2/:
>PALETTE COLOR = Pixel data describe a color image with a single sample per pixel (single image plane). The pixel value is used as an index into each of the Red, Blue, and Green Palette Color Lookup Tables (0028,1101-1103&1201-1203). This value may be used only when Samples per Pixel (0028,0002) has a value of 1. When the Photometric Interpretation is Palette Color; Red, Blue, and Green Palette Color Lookup Tables shall be present.

These values must be preserved:
* (0028,1101-1103&1201-1203)
* Samples per Pixel (0028,0002)

**Comment by jeffmax** [comment]
Thanks!
