### ISSUE TITLE
Set Fields Indicating Anonymization

### ISSUE THREAD

**Issue by cancan101** [chop-dbhi/dicom-anon#15]
After running set "Patient Identity Removed" (0012,0062) = 'YES'
and "De-identification Method" (0012,0063) to something like "dicom-anon"

See: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.html

**Comment by jeffmax** [comment]
Good idea- will do.

**Comment by jeffmax** [comment]
This is done, but the values method has been put into 0012,0064, De-identification Method Code Sequence, describing the profile, Clean or Clean Descriptors.
