### ISSUE TITLE
Interested in injecting some logic into fields

### ISSUE THREAD

**Issue by alexfelmeister** [chop-dbhi/dicom-anon#21]
for example: 
- specific study id specified in the command into the patient and accession numbers
- logic to change the study date to an age at study.

**Comment by alexfelmeister** [comment]
@r3m0chop let's discuss for cbttc image project.

**Comment by jeffmax** [comment]
Let me know if I can be of any help.

**Comment by alexfelmeister** [comment]
I have this working just fine, but have a pretty specific de-identification workflow in mind that I am not 100% sure where to implement (white list, the dat file, change up the code etc.)  Let's chat when you can.

**Comment by alexfelmeister** [comment]
@jeffmax just FYI, your suggestion works, e.g.
Acquisition Date	(0008,0022)
N	Y	K					C

That will keep it there and I can hand change the calculation after. At least for now. Going to close this and possibly do the calculations in our image server area after the full de-ident.
