### ISSUE TITLE
Dictionary Key Error, also generated file lacks required valid dicom headers. 

### ISSUE THREAD

**Issue by walterwang** [chop-dbhi/dicom-anon#24]
```
File "dicom_anon.py", line 552, in anonymize
    ds.file_meta[MEDIA_STORAGE_SOP_INSTANCE_UID].value = ds[SOP_INSTANCE_UID].value
  File "/home/anaconda3/envs/rad/lib/python3.6/site-packages/pydicom/dataset.py", line 582, in __getitem__
    data_elem = dict.__getitem__(self, tag)
KeyError: (0008, 0018)
```
It looks like SOP_INSTANCE_UID is removed along with other required tags from the walking. Is this script still working for others?

**Comment by jeffmax** [comment]
Can you try running in python 2.7- this has not been upgraded to python 3 yet. It also requires a specific version of pydicom as specified in the requirements file.
