### ISSUE TITLE
Bug ValueError not Supported Python 3.7.2

### ISSUE THREAD

**Issue by raluca-san** [chop-dbhi/dicom-anon#25]
File "//develop/dicom-anon-master/dicom_anon.py", line 603
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Not Supported in Python 3.7.2

**Comment by raluca-san** [comment]
replaced with Exception, not sure if the best solution, but good workaround

**Comment by jeffmax** [comment]
@raluca-san I think this is related to Python 3, we have not upgraded this to officially support Python 3, it was written for Python 2.7

**Comment by jeffmax** [comment]
Try 

    ValueError as e:

**Comment by jeffmax** [comment]
I ran  the tests (run_tests.sh) under Python 3 at it is failing, this needs to be looked into.

**Comment by jeffmax** [comment]
@raluca-san Just an FYI, this package is not tested under Python 3 and will not work properly. I recommend you use Python 2.7.
