### ISSUE TITLE
Questions Around Exception Handling

### ISSUE THREAD

**Issue by cancan101** [chop-dbhi/dicom-anon#4]
Looking [here](https://github.com/chop-dbhi/dicom-anon/blob/4a6f06887459e72fb07ba17c28ad2fa4747c74e0/dicom_anon.py#L701) why does an `IOError` stop execution whereas an unhanded `Exception` is `continue`d?

**Comment by jeffmax** [comment]
Excellent question- I don't remember. It likely had to do with a specific issue I ran into locally, but you are right to point it out. It might have been that in the situation where I got an IOError I wasn't even able to move the file to quarantine. It could definitely use a comment. I appreciate the second set of eyes on this thing.

**Comment by blakedewey** [comment]
I think this can be closed. I changed the Exception to a pydicom specific error.

**Comment by jeffmax** [comment]
Agreed- this make sense now that you have called out the second error out as InvalidDicomError. I expect I assumed an IOError meant there was something wrong with the drive or mount and indicated nothing further would work. Thanks again.
